<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [13]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mult(A,B):

    num_col_a = len(A[0])#Calculating the number of columns in first matrix i.e A
    num_rows_b = len(B)  #Calculating rhe number of rows in second matrix i.e B

    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))] #Initializing the result matrix to zero

    if num_col_a == num_rows_b:  #Checking whether the number of columns of first matrix is equal to number of rows in second matrix
        for row_a_index, row_a in enumerate(A):
            for col_index, col_b in enumerate(zip(*B)):
                result[row_a_index][col_index] = sum(a * b for a, b in zip(row_a, col_b))

    return result

A = [[1,2],[3,4]]
B = [[1,2,3,4,5], [5,6,7,8,9]]
print(matrix_mult(A,B))

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [24]:
from random import uniform
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
from random import uniform
# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    first=0
    scale=sum(A)
    random_value=uniform(0,scale)
    for i in A:
        last_value=first+i
        first=last_value
        if random_value<=last_value:
            break
    return i
        

def sampling_based_on_magnitued():
   
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number,end=",")
A =[0,5,27,6,13,28,100,45,10,79]
sampling_based_on_magnitued()

100,27,13,13,79,27,100,6,28,100,45,100,79,45,45,27,27,27,27,10,100,100,100,79,100,28,79,28,79,100,100,79,100,79,45,79,100,79,79,100,100,79,45,100,27,79,100,45,100,100,13,100,10,45,45,79,100,13,100,45,79,5,100,79,79,100,45,45,10,79,45,100,5,28,10,100,79,100,13,100,27,45,79,79,45,100,45,79,79,27,28,79,45,6,28,100,45,100,79,

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [4]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(str):
    # write your code
    mod_str1=re.sub('[^0-9]','',str)
    mod_str=re.sub("\d","#",mod_str1)
    return mod_str # modified string which is after replacing the # with digits

String=input("Enter your string:")
mod=replace_digits(String)
print("\nString before Modification = {0} and String after Modification={1}".format(String,mod))

Enter your string:#2a$#b%c%561#

String before Modification = #2a$#b%c%561# and String after Modification=####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [18]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(marks):
    demo_marks=list(marks)
    # write code for computing top top 5 students
     # compute this
    # write code for computing top least 5 students
    demo_marks.sort()
    least_5_students =[]
    for i in range(5):
      least_5_students.append(marks.index(demo_marks[i]))
    students_within_25_and_75 =[]
    for i in range(len(demo_marks)):
      if(demo_marks[i]>25 and demo_marks[i]<75):
        students_within_25_and_75.append(marks.index(demo_marks[i]))
    demo_marks.reverse()
    top_5_students =[]
    for i in range(5):
      top_5_students.append(marks.index(demo_marks[i]))
     # compute this
    # write code for computing top least 5 students
   # compute this
    
    return top_5_students,least_5_students,students_within_25_and_75
students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(marks)
print('a.')
for i in range(len(top_5_students)):
  print(students[top_5_students[i]] +' '+ str(marks[top_5_students[i]]))
print('b.')
for i in range(len( least_5_students)):
  print(students[ least_5_students[i]]+' '+ str(marks[ least_5_students[i]]))
print('c.')
for i in range(len(students_within_25_and_75)):
  print(students[students_within_25_and_75[i]]+' '+ str(marks[students_within_25_and_75[i]]))

a.
student8 98
student10 80
student2 78
student5 48
student7 47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [6]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    closest_points_to_p_values=[]
    closest_points_to_p=[]
    for i in range(len(S)):
        m=math.acos(((S[i][0]*P[0])+(S[i][1]*P[1]))/((math.sqrt((S[i][0]*S[i][0])+(S[i][1]*S[i][1])))*(math.sqrt((P[0]*P[0])+(P[1]*P[1])))))
        closest_points_to_p_values.append(m)
    demo_ans=list(closest_points_to_p_values)
    demo_ans.sort()
    for i in range(5):
        closest_points_to_p.append(S[closest_points_to_p_values.index(demo_ans[i])])

    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [7]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red, blue, line):
    sign_of_equation_with_red_point_tuple = -1

    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0:
        sign_of_equation_with_red_point_tuple = 1
    for red_point in red:
        if sign_of_equation_with_red_point_tuple == 1 and eval(
                line.replace('x', '*%s' % red_point[0]).replace('y', '*%s' % red_point[1])) < 0:
            return 'NO'
        if sign_of_equation_with_red_point_tuple == -1 and eval(
                line.replace('x', '*%s' % red_point[0]).replace('y', '*%s' % red_point[1])) > 0:
            return 'NO'

    # Now the same set of two traversal for the blue-points tuples

    sign_of_equation_with_blue_point_tuple = -1 * sign_of_equation_with_red_point_tuple

    for blue_point in blue:
        if sign_of_equation_with_blue_point_tuple == 1 and eval(
                line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) < 0:
            return 'NO'
        if sign_of_equation_with_blue_point_tuple == -1 and eval(
                line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) > 0:
            return 'NO'

    return 'YES'

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    lst=string.split(',')
    for i in range(len(lst)):
        if lst[i].isdigit():
            for j in range(i+1):
                lst[j]=int(lst[i])//(i+1)
            new_index=i
            new_value=int(lst[i])
            break
    for i in range(new_index+1,len(lst)):
        if lst[i].isdigit():
            temp=(new_value+int(lst[i]))//(i-new_index+1)
            for j in range(new_index,i+1):
                lst[j]=temp
            new_index=i
            new_value=int(lst[i])
    try:
        for i in range(new_index+1,len(lst)):
            if not(lst[i].isdigit()):
                count=lst.count('_')
                break
        temp1=new_value//(count+1)
        for i in range(new_index,len(lst)):
            lst[i]=temp1
    except:
        pass
    return lst

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [9]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
from fractions import Fraction


def compute_conditional_probability(A):
    # From the given 2-D Matrix A
    # Set a dictionary containing the count of all the F and S together
    # This dictionary will have as many elements as the given Matrix A
    dictionary_f_intersection_s = dict()
    for item_list in A:
        dict_key = str(item_list[0]) + str(item_list[1])
        dictionary_f_intersection_s[dict_key] = 0
    # print(dictionary_f_intersection_s)
    # {'F1S1': 0, 'F2S2': 0, 'F3S3': 0, 'F1S2': 0, 'F2S3': 0, 'F3S2': 0, 'F2S1': 0, 'F4S1': 0, 'F4S3': 0, 'F5S1': 0}

    # Set a dictionary containing the count of all the S only
    dictionary_s = {'S1': 0, 'S2': 0, 'S3': 0}

    for i in range(len(A)):
        f_intersection_s_key = A[i][0] + A[i][1]
        dictionary_f_intersection_s[f_intersection_s_key] += 1

        s_key = A[i][1]
        dictionary_s[s_key] += 1

    # print('a. P(F=F1|S==S1)=', Fraction(dictionary_f_intersection_s['F1S1'] / dictionary_s['S1']).limit_denominator(), ' P(F=F1|S==S2)=', Fraction(dictionary_f_intersection_s['F1S2'] / dictionary_s['S2']).limit_denominator(), ' P(F=F1|S==S3)=', Fraction(dictionary_f_intersection_s.get('F1S3', 0) / dictionary_s['S3']).limit_denominator())
    idx = 97
    print('{0:c}. P(F=F1|S==S1)={F1S1}/{S1}, P(F=F1|S==S2)={F1S2}/{S2}, P(F=F1|S==S3)={F1S3}/{S3}'.format(idx,
                                                                                                          F1S1=dictionary_f_intersection_s.get(
                                                                                                              'F1S1',
                                                                                                              0), S1=
                                                                                                          dictionary_s[
                                                                                                              'S1'],
                                                                                                          F1S2=dictionary_f_intersection_s.get(
                                                                                                              'F1S2',
                                                                                                              0), S2=
                                                                                                          dictionary_s[
                                                                                                              'S2'],
                                                                                                          F1S3=dictionary_f_intersection_s.get(
                                                                                                              'F1S3',
                                                                                                              0), S3=
                                                                                                          dictionary_s[
                                                                                                              'S3']))

    print('{0:c}. P(F=F2|S==S1)={F2S1}/{S1}, P(F=F2|S==S2)={F2S2}/{S2}, P(F=F2|S==S3)={F2S3}/{S3}'.format(idx+1,
                                                                                                          F2S1=dictionary_f_intersection_s.get(
                                                                                                              'F2S1',
                                                                                                              0), S1=
                                                                                                          dictionary_s[
                                                                                                              'S1'],
                                                                                                          F2S2=dictionary_f_intersection_s.get(
                                                                                                              'F2S2',
                                                                                                              0), S2=
                                                                                                          dictionary_s[
                                                                                                              'S2'],
                                                                                                          F2S3=dictionary_f_intersection_s.get(
                                                                                                              'F2S3',
                                                                                                              0), S3=
                                                                                                          dictionary_s[
                                                                                                              'S3']))

    print('{0:c}. P(F=F3|S==S1)={F3S1}/{S1}, P(F=F3|S==S2)={F3S2}/{S2}, P(F=F3|S==S3)={F3S3}/{S3}'.format(idx + 2,
                                                                                                          F3S1=dictionary_f_intersection_s.get(
                                                                                                              'F3S1',
                                                                                                              0), S1=
                                                                                                          dictionary_s[
                                                                                                              'S1'],
                                                                                                          F3S2=dictionary_f_intersection_s.get(
                                                                                                              'F3S2',
                                                                                                              0), S2=
                                                                                                          dictionary_s[
                                                                                                              'S2'],
                                                                                                          F3S3=dictionary_f_intersection_s.get(
                                                                                                              'F3S3',
                                                                                                              0), S3=
                                                                                                          dictionary_s[
                                                                                                              'S3']))

    print('{0:c}. P(F=F4|S==S1)={F4S1}/{S1}, P(F=F4|S==S2)={F4S2}/{S2}, P(F=F4|S==S3)={F4S3}/{S3}'.format(idx + 2,
                                                                                                          F4S1=dictionary_f_intersection_s.get(
                                                                                                              'F4S1',
                                                                                                              0), S1=
                                                                                                          dictionary_s[
                                                                                                              'S1'],
                                                                                                          F4S2=dictionary_f_intersection_s.get(
                                                                                                              'F4S2',
                                                                                                              0), S2=
                                                                                                          dictionary_s[
                                                                                                              'S2'],
                                                                                                          F4S3=dictionary_f_intersection_s.get(
                                                                                                              'F4S3',
                                                                                                              0), S3=
                                                                                                          dictionary_s[
                                                                                                              'S3']))

    print('{0:c}. P(F=F5|S==S1)={F5S1}/{S1}, P(F=F5|S==S2)={F5S2}/{S2}, P(F=F5|S==S3)={F5S3}/{S3}'.format(idx + 2,
                                                                                                          F5S1=dictionary_f_intersection_s.get(
                                                                                                              'F5S1',
                                                                                                              0), S1=
                                                                                                          dictionary_s[
                                                                                                              'S1'],
                                                                                                          F5S2=dictionary_f_intersection_s.get(
                                                                                                              'F5S2',
                                                                                                              0), S2=
                                                                                                          dictionary_s[
                                                                                                              'S2'],
                                                                                                          F5S3=dictionary_f_intersection_s.get(
                                                                                                              'F5S3',
                                                                                                              0), S3=
                                                                                                          dictionary_s[
                                                                                                              'S3']))



# # you can free to change all these codes/structure
# def compute_conditional_probabilites(A):
#     # your code
#     # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probability(A)

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
c. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
c. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [10]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    S1 = S1.split(" ")
    S1 = set(S1)
    S2 = S2.split(" ")
    S2 = set(S2)
    a = len(S1.intersection(S2)) #Number of common words between S1, S2
    b = list(S1 - S2)            #Words in S1 but not in S2
    c = list(S2 - S1)            #Words in S2 but not in S1
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c)

7 ['F', 'first', '5'] ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [17]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import math
def compute_log_loss(A):
    # your code
    values=[]
    for i in range(len(A)):
        m=((A[i][0]*(math.log10(A[i][1])))+((1-A[i][0])*(math.log10(1-A[i][1]))))
        values.append(m)
    loss=0
    for i in range(len(values)):
        loss+=values[i]
    loss=loss/len(values)
    loss=(-1)*loss        
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(round(loss,7))

0.4243099
